/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Cardfaces": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "user": string
    }
    "Email": {
      "sender": string
      "type": "sst.aws.Email"
    }
    "Migrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MyRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "StaticSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
