/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RandomHeroImport } from './routes/random-hero'
import { Route as RandomImport } from './routes/random'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as SetsSetIdImport } from './routes/sets/$setId'
import { Route as CardsCardIdImport } from './routes/cards/$cardId'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLoginImport } from './routes/auth/login'

// Create/Update Routes

const RandomHeroRoute = RandomHeroImport.update({
  path: '/random-hero',
  getParentRoute: () => rootRoute,
} as any)

const RandomRoute = RandomImport.update({
  path: '/random',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const SetsSetIdRoute = SetsSetIdImport.update({
  path: '/sets/$setId',
  getParentRoute: () => rootRoute,
} as any)

const CardsCardIdRoute = CardsCardIdImport.update({
  path: '/cards/$cardId',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/random': {
      preLoaderRoute: typeof RandomImport
      parentRoute: typeof rootRoute
    }
    '/random-hero': {
      preLoaderRoute: typeof RandomHeroImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/cards/$cardId': {
      preLoaderRoute: typeof CardsCardIdImport
      parentRoute: typeof rootRoute
    }
    '/sets/$setId': {
      preLoaderRoute: typeof SetsSetIdImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthenticatedRoute,
  AboutRoute,
  RandomRoute,
  RandomHeroRoute,
  AuthLoginRoute,
  AuthSignupRoute,
  CardsCardIdRoute,
  SetsSetIdRoute,
  ProfileIndexRoute,
])

/* prettier-ignore-end */
