/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RandomImport } from './routes/random'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as SetsSetIdImport } from './routes/sets/$setId'
import { Route as CardsCardIdImport } from './routes/cards/$cardId'

// Create/Update Routes

const RandomRoute = RandomImport.update({
  path: '/random',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SetsSetIdRoute = SetsSetIdImport.update({
  path: '/sets/$setId',
  getParentRoute: () => rootRoute,
} as any)

const CardsCardIdRoute = CardsCardIdImport.update({
  path: '/cards/$cardId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/random': {
      preLoaderRoute: typeof RandomImport
      parentRoute: typeof rootRoute
    }
    '/cards/$cardId': {
      preLoaderRoute: typeof CardsCardIdImport
      parentRoute: typeof rootRoute
    }
    '/sets/$setId': {
      preLoaderRoute: typeof SetsSetIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthenticatedRoute,
  AboutRoute,
  RandomRoute,
  CardsCardIdRoute,
  SetsSetIdRoute,
])

/* prettier-ignore-end */
